# Generated by Django 3.1.7 on 2021-05-02 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('idcontact', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Контакта')),
                ('contact_name', models.CharField(max_length=45, verbose_name='Имя')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('contact_email', models.CharField(blank=True, max_length=45, verbose_name='Email')),
                ('contact_two_name', models.CharField(blank=True, max_length=45, verbose_name='Запасное Имя')),
                ('contact_two_phone', models.CharField(blank=True, max_length=20, verbose_name='Запасной номер телефона')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('idevent', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Мероприятия')),
                ('event_title', models.CharField(default=None, max_length=45, verbose_name='Название')),
                ('event_datetime', models.DateTimeField(default=None, verbose_name='Дата и время мероприятия')),
                ('event_location', models.CharField(default=None, max_length=80, verbose_name='Место мероприятия')),
                ('event_person_count', models.CharField(blank=True, default=None, max_length=45, verbose_name='Число человек')),
                ('event_director_full_name', models.CharField(default=None, max_length=45, verbose_name='ФИО Организатора')),
                ('event_director_phone', models.CharField(default=None, max_length=45, verbose_name='Телефон Организатора')),
                ('event_director_email', models.CharField(blank=True, default=None, max_length=45, verbose_name='Email Организатора')),
                ('event_description', models.TextField(default=None, max_length=200, verbose_name='Дополнительное описание')),
            ],
            options={
                'verbose_name': 'Мероприятия',
                'verbose_name_plural': 'Мероприятия',
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='FoundPets',
            fields=[
                ('idfound_pet', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Найденного животного')),
                ('found_pet_color', models.CharField(default=None, max_length=45, verbose_name='Цвет шерсти')),
                ('found_pet_age', models.CharField(blank=True, default=None, max_length=25, verbose_name='Примерный возраст')),
                ('found_pet_gender', models.CharField(blank=True, choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default=None, max_length=10, verbose_name='Пол')),
                ('found_pet_health', models.CharField(blank=True, default=None, max_length=70, verbose_name='Состояние здоровья')),
                ('found_pet_found_datetime', models.DateTimeField(default=None, verbose_name='Дата и время нахождения')),
                ('found_pet_found_location', models.CharField(default=None, max_length=100, verbose_name='Место нахождения')),
                ('found_pet_description', models.TextField(blank=True, default=None, max_length=200, verbose_name='Дополнительное описание')),
            ],
            options={
                'verbose_name': 'Найденные животные',
                'verbose_name_plural': 'Найденные животные',
                'db_table': 'found_pet',
            },
        ),
        migrations.CreateModel(
            name='LostPets',
            fields=[
                ('idlost_pet', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Потерянного животного')),
                ('lost_pet_name', models.CharField(default=None, max_length=45, verbose_name='Кличка')),
                ('lost_pet_gender', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default=None, max_length=10, verbose_name='Пол')),
                ('lost_pet_age', models.CharField(default=None, max_length=25, verbose_name='Возраст')),
                ('lost_pet_color', models.CharField(default=None, max_length=45, verbose_name='Цвет шерсти')),
                ('lost_pet_size', models.CharField(choices=[('Крошечный', 'Крошечный'), ('Небольшой', 'Небольшой'), ('Средний', 'Средний'), ('Крупный', 'Крупный')], default=None, max_length=15, verbose_name='Размер')),
                ('lost_pet_breed', models.CharField(default=None, max_length=45, verbose_name='Порода')),
                ('lost_pet_description', models.TextField(blank=True, default=None, max_length=200, verbose_name='Описание')),
                ('lost_pet_lost_datetime', models.DateTimeField(default=None, verbose_name='Дата и время потери')),
                ('lost_pet_lost_location', models.CharField(default=None, max_length=80, verbose_name='Место потери')),
            ],
            options={
                'verbose_name': 'Потерянные животные',
                'verbose_name_plural': 'Потерянные животные',
                'db_table': 'lost_pet',
            },
        ),
        migrations.CreateModel(
            name='PetsBreed',
            fields=[
                ('idpet_breed', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Породы')),
                ('pet_breed', models.CharField(max_length=45, verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Породы животных',
                'verbose_name_plural': 'Породы животных',
                'db_table': 'pet_breed',
            },
        ),
        migrations.CreateModel(
            name='Shelters',
            fields=[
                ('idshelter', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Приюта')),
                ('shelter_place', models.CharField(blank=True, choices=[('Муниципальный приют', 'Муниципальный приют'), ('Частный приют', 'Частный приют')], max_length=45, verbose_name='Тип приюта')),
                ('shelter_name', models.CharField(blank=True, max_length=45, verbose_name='Название приюта')),
                ('shelter_region', models.CharField(blank=True, max_length=60, verbose_name='Регион')),
                ('shelter_city', models.CharField(max_length=60, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Приюты',
                'verbose_name_plural': 'Приюты',
                'db_table': 'shelter',
            },
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('idpet', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Животного')),
                ('pet_name', models.CharField(max_length=100, verbose_name='Имя животного')),
                ('pet_status', models.CharField(choices=[('Ищет дом', 'Ищет дом'), ('Нашел дом', 'Нашел дом')], max_length=15, verbose_name='Статус животного')),
                ('pet_gender', models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10, verbose_name='Пол')),
                ('pet_age', models.CharField(max_length=20, verbose_name='Возраст')),
                ('pet_vaccination', models.CharField(choices=[('Да', 'Да'), ('Частично', 'Частично'), ('Нет', 'Нет')], max_length=10, verbose_name='Вакцинация')),
                ('pet_sterilization', models.CharField(choices=[('Да', 'Да'), ('Частично', 'Частично'), ('Нет', 'Нет')], max_length=10, verbose_name='Стерилизация')),
                ('pet_toilet', models.CharField(blank=True, max_length=25, verbose_name='Приучен к туалету')),
                ('pet_size', models.CharField(choices=[('Крошечный', 'Крошечный'), ('Небольшой', 'Небольшой'), ('Средний', 'Средний'), ('Крупный', 'Крупный')], max_length=15, verbose_name='Размер')),
                ('pet_type', models.CharField(max_length=100, verbose_name='Тип')),
                ('pet_breed', models.CharField(max_length=60, verbose_name='Порода')),
                ('pet_wool_length', models.CharField(choices=[('Короткая', 'Короткая'), ('Средняя', 'Средняя'), ('Длинная', 'Длинная')], max_length=10, verbose_name='Длина шерсти')),
                ('pet_wool_color', models.CharField(max_length=50, verbose_name='Цвет шерсти')),
                ('pet_weight', models.CharField(max_length=25, verbose_name='Вес')),
                ('pet_health', models.CharField(max_length=100, verbose_name='Здоровье')),
                ('pet_privicies', models.TextField(blank=True, max_length=150, verbose_name='Особенности')),
                ('pet_temperament', models.CharField(max_length=30, verbose_name='Темперамент')),
                ('pet_human_centred', models.CharField(blank=True, max_length=30, verbose_name='Ориентированность на людей')),
                ('pet_attitude_chlidren', models.CharField(blank=True, max_length=30, verbose_name='Ориентированность на детей')),
                ('pet_attitude_cat', models.CharField(blank=True, max_length=30, verbose_name='Ориентированность на котов')),
                ('pet_attitude_other_pets', models.CharField(blank=True, max_length=30, verbose_name='Ориентированность на других собак')),
                ('pet_keeping', models.CharField(blank=True, max_length=50, verbose_name='Содержание')),
                ('pet_live_in_apartment', models.CharField(blank=True, max_length=20, verbose_name='Приучен к жизни в квартире')),
                ('pet_accustomed_to_a_leash', models.CharField(blank=True, max_length=20, verbose_name='Приучен к поводку')),
                ('pet_training', models.CharField(blank=True, max_length=20, verbose_name='Приучен к дрессировкам')),
                ('pet_location', models.CharField(max_length=45, verbose_name='Место нахождения')),
                ('petImagePath', models.ImageField(upload_to='Pets_images', verbose_name='Фото животного')),
                ('contact_idcontact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contact')),
                ('pet_breed_idpet_breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.petsbreed')),
                ('shelter_idshelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shelters')),
            ],
            options={
                'verbose_name': 'Животные',
                'verbose_name_plural': 'Животные',
                'db_table': 'pet',
            },
        ),
    ]
