# Generated by Django 3.1.7 on 2021-03-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idpet', models.IntegerField(verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100, verbose_name='Имя животного')),
                ('pet_status', models.CharField(max_length=45, verbose_name='Статус животного')),
                ('pet_gender', models.CharField(max_length=10, verbose_name='Пол')),
                ('pet_age', models.CharField(max_length=100, verbose_name='Возраст')),
                ('pet_vaccination', models.CharField(max_length=10, verbose_name='Вакцинация')),
                ('pet_sterilization', models.CharField(max_length=10, verbose_name='Стерилизация')),
                ('pet_toilet', models.CharField(max_length=10, verbose_name='Приучен к туалету')),
                ('pet_size', models.CharField(max_length=15, verbose_name='Размер')),
                ('pet_type', models.CharField(max_length=100, verbose_name='Тип')),
                ('pet_breed', models.CharField(max_length=100, verbose_name='Порода')),
                ('pet_wool_length', models.CharField(max_length=100, verbose_name='Длина шерсти')),
                ('pet_wool_color', models.CharField(max_length=100, verbose_name='Цвет шерсти')),
                ('pet_weight', models.CharField(max_length=50, verbose_name='Вес')),
                ('pet_health', models.CharField(max_length=100, verbose_name='Здоровье')),
                ('pet_privicies', models.CharField(max_length=100, verbose_name='Особенности')),
                ('pet_temperament', models.CharField(max_length=30, verbose_name='Темперамент')),
                ('pet_human_centred', models.CharField(max_length=30, verbose_name='Ориентированность на людей')),
                ('pet_attitude_chlidren', models.CharField(max_length=30, verbose_name='Ориентированность на детей')),
                ('pet_attitude_cat', models.CharField(max_length=30, verbose_name='Ориентированность на котов')),
                ('pet_attitude_other_pets', models.CharField(max_length=30, verbose_name='Ориентированность на других собак')),
                ('pet_keeping', models.CharField(max_length=50, verbose_name='Содержание')),
                ('pet_live_in_apartment', models.CharField(max_length=20, verbose_name='Приучен к жизни в квартире')),
                ('pet_accustomed_to_a_leash', models.CharField(max_length=20, verbose_name='Приучен к поводку')),
                ('pet_training', models.CharField(max_length=20, verbose_name='Приучен к дрессировкам')),
                ('pet_location', models.CharField(max_length=45, verbose_name='Место нахождения')),
                ('contact_idcontact', models.IntegerField(max_length=20, verbose_name='Контакты')),
                ('shelter_idshelter', models.IntegerField(max_length=20, verbose_name='Номер приюта')),
            ],
        ),
    ]
