# Generated by Django 3.1.7 on 2021-05-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.CharField(blank=True, default=None, max_length=45, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_two_name',
            field=models.CharField(blank=True, default=None, max_length=45, verbose_name='Запасное Имя'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_two_phone',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='Запасной номер телефона'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_accustomed_to_a_leash',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='Приучен к поводку'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_attitude_chlidren',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Ориентированность на детей'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_attitude_other_pets',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Ориентированность на других собак'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_human_centred',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Ориентированность на людей'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_keeping',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_live_in_apartment',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='Приучен к жизни в квартире'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_privicies',
            field=models.TextField(blank=True, default=None, max_length=150, verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_toilet',
            field=models.CharField(blank=True, default=None, max_length=25, verbose_name='Приучен к туалету'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_training',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='Приучен к дрессировкам'),
        ),
        migrations.AlterField(
            model_name='shelters',
            name='shelter_name',
            field=models.CharField(blank=True, default=None, max_length=45, verbose_name='Название приюта'),
        ),
        migrations.AlterField(
            model_name='shelters',
            name='shelter_place',
            field=models.CharField(blank=True, choices=[('Муниципальный приют', 'Муниципальный приют'), ('Частный приют', 'Частный приют')], default=None, max_length=45, verbose_name='Тип приюта'),
        ),
        migrations.AlterField(
            model_name='shelters',
            name='shelter_region',
            field=models.CharField(blank=True, default=None, max_length=60, verbose_name='Регион'),
        ),
    ]
