# Generated by Django 3.1.7 on 2021-05-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210502_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petsbreed',
            options={'ordering': ['idpet_breed'], 'verbose_name': 'Породы животных', 'verbose_name_plural': 'Породы животных'},
        ),
        migrations.RenameField(
            model_name='petsbreed',
            old_name='pet_breed',
            new_name='breed',
        ),
    ]
