# Generated by Django 3.1.7 on 2021-05-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210503_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='pets',
            name='pet_wool_color_extra',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Дополнительный цвет шерсти'),
        ),
    ]
