# Generated by Django 3.1.7 on 2021-03-13 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210313_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='idpet',
        ),
    ]
