# Generated by Django 3.1.7 on 2021-05-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pets_pet_wool_color_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='pet_wool_color_extra',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Дополнительный цвет шерсти'),
        ),
    ]
