# Generated by Django 3.1.7 on 2021-04-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_pets_idpet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('idcontact', models.AutoField(primary_key=True, serialize=False, verbose_name='Id_contact')),
                ('contact_mane', models.CharField(max_length=45, verbose_name='Имя')),
                ('contact_phone', models.CharField(max_length=45, verbose_name='Номер телефона')),
                ('contact_email', models.CharField(blank=True, max_length=45, verbose_name='Email')),
                ('contact_two_name', models.CharField(blank=True, max_length=45, verbose_name='Запасное Имя')),
                ('contact_two_phone', models.CharField(blank=True, max_length=45, verbose_name='Запасной номер телефона')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
                'db_table': 'contact',
            },
        ),
        migrations.AlterModelOptions(
            name='pets',
            options={'verbose_name': 'Животные', 'verbose_name_plural': 'Животные'},
        ),
        migrations.RemoveField(
            model_name='pets',
            name='id',
        ),
        migrations.AddField(
            model_name='pets',
            name='idpet',
            field=models.AutoField(default='default id', primary_key=True, serialize=False, verbose_name='Id_pet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pets',
            name='petImagePath',
            field=models.ImageField(default='default image', upload_to='Pets_images', verbose_name='Фото животного'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_accustomed_to_a_leash',
            field=models.CharField(blank=True, max_length=20, verbose_name='Приучен к поводку'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_attitude_cat',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ориентированность на котов'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_attitude_chlidren',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ориентированность на детей'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_attitude_other_pets',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ориентированность на других собак'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_human_centred',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ориентированность на людей'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_keeping',
            field=models.CharField(blank=True, max_length=50, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_live_in_apartment',
            field=models.CharField(blank=True, max_length=20, verbose_name='Приучен к жизни в квартире'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_privicies',
            field=models.CharField(blank=True, max_length=100, verbose_name='Особенности'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_size',
            field=models.CharField(choices=[('Крошечный', 'Крошечный'), ('Небольшой', 'Небольшой'), ('Средний', 'Средний'), ('Крупный', 'Крупный')], max_length=15, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_status',
            field=models.CharField(choices=[('Ищет дом', 'Ищет дом'), ('Нашел дом', 'Нашел дом')], max_length=45, verbose_name='Статус животного'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_sterilization',
            field=models.CharField(choices=[('Да', 'Да'), ('Частично', 'Частично'), ('Нет', 'Нет')], max_length=10, verbose_name='Стерилизация'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_toilet',
            field=models.CharField(blank=True, max_length=25, verbose_name='Приучен к туалету'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_training',
            field=models.CharField(blank=True, max_length=20, verbose_name='Приучен к дрессировкам'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_vaccination',
            field=models.CharField(choices=[('Да', 'Да'), ('Частично', 'Частично'), ('Нет', 'Нет')], max_length=10, verbose_name='Вакцинация'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_wool_length',
            field=models.CharField(choices=[('Короткая', 'Короткая'), ('Средняя', 'Средняя'), ('Длинная', 'Длинная')], max_length=100, verbose_name='Длина шерсти'),
        ),
    ]
