# Generated by Django 3.1.7 on 2021-05-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210509_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pets',
            old_name='pet_attitude_chlidren',
            new_name='pet_attitude_children',
        ),
    ]
