# Generated by Django 3.1.7 on 2021-05-12 12:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210510_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpets',
            name='found_pet_found_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время нахождения'),
        ),
        migrations.AlterField(
            model_name='lostpets',
            name='lost_pet_lost_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время потери'),
        ),
    ]
