# Generated by Django 3.1.7 on 2021-05-12 12:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210512_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpets',
            name='found_pet_found_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 12, 12, 6, 27, 555063, tzinfo=utc), verbose_name='Дата и время нахождения'),
        ),
    ]
