# Generated by Django 3.1.7 on 2021-05-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210512_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundpets',
            name='found_contact_email',
            field=models.CharField(blank=True, default=None, max_length=45, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='foundpets',
            name='found_contact_name',
            field=models.CharField(default=None, max_length=45, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='foundpets',
            name='found_contact_phone',
            field=models.CharField(default='None', max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foundpets',
            name='found_pet_size',
            field=models.CharField(choices=[('Крошечный', 'Крошечный'), ('Небольшой', 'Небольшой'), ('Средний', 'Средний'), ('Крупный', 'Крупный')], default='None', max_length=15, verbose_name='Размер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostpets',
            name='lost_contact_email',
            field=models.CharField(blank=True, default=None, max_length=45, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='lostpets',
            name='lost_contact_name',
            field=models.CharField(default=None, max_length=45, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='lostpets',
            name='lost_contact_phone',
            field=models.CharField(default='None', max_length=20, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foundpets',
            name='found_pet_found_location',
            field=models.CharField(default=None, max_length=100, verbose_name='Город'),
        ),
    ]
