# Generated by Django 3.1.7 on 2021-05-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210512_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundpets',
            name='found_pet_name',
            field=models.CharField(blank=True, default=None, max_length=45, verbose_name='Кличка'),
        ),
    ]
