# Generated by Django 3.1.7 on 2021-05-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_foundpets_found_pet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundpets',
            name='found_pet_status',
            field=models.CharField(choices=[('Найдена', 'Найдена'), ('Дома', 'Дома')], default='None', max_length=15, verbose_name='Статус животного'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostpets',
            name='lost_pet_status',
            field=models.CharField(choices=[('Пропала', 'Пропала'), ('Дома', 'Дома')], default='None', max_length=15, verbose_name='Статус животного'),
            preserve_default=False,
        ),
    ]
