# Generated by Django 3.1.7 on 2021-05-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210512_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundpets',
            name='found_petImagePath',
            field=models.ImageField(default='default_img', upload_to='Found_Pets_images', verbose_name='Фото животного'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostpets',
            name='lost_petImagePath',
            field=models.ImageField(default='default_img', upload_to='Lost_Pets_images', verbose_name='Фото животного'),
            preserve_default=False,
        ),
    ]
