# Generated by Django 3.1.7 on 2021-05-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210512_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundpets',
            name='found_pet_breed',
            field=models.CharField(default=None, max_length=60, verbose_name='Порода'),
        ),
    ]
