# Generated by Django 3.1.7 on 2021-05-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_foundpets_found_pet_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpets',
            name='found_pet_breed',
            field=models.CharField(blank=True, default=None, max_length=60, verbose_name='Порода'),
        ),
    ]
