# Generated by Django 3.1.7 on 2021-05-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20210512_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_description',
            field=models.TextField(default=None, max_length=400, verbose_name='Дополнительное описание'),
        ),
        migrations.AlterField(
            model_name='foundpets',
            name='found_pet_description',
            field=models.TextField(blank=True, default=None, max_length=400, verbose_name='Дополнительное описание'),
        ),
        migrations.AlterField(
            model_name='lostpets',
            name='lost_pet_breed',
            field=models.CharField(default=None, max_length=60, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='lostpets',
            name='lost_pet_description',
            field=models.TextField(blank=True, default=None, max_length=400, verbose_name='Описание'),
        ),
    ]
