# Generated by Django 3.1.7 on 2021-05-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210512_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpets',
            name='found_pet_description',
            field=models.TextField(blank=True, default=None, verbose_name='Дополнительное описание'),
        ),
        migrations.AlterField(
            model_name='lostpets',
            name='lost_pet_description',
            field=models.TextField(blank=True, default=None, verbose_name='Описание'),
        ),
    ]
