# Generated by Django 3.1.7 on 2021-05-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210512_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpets',
            name='found_pet_status',
            field=models.CharField(blank=True, choices=[('Найдена', 'Найдена'), ('Дома', 'Дома')], default='Найдена', max_length=15, verbose_name='Статус животного'),
        ),
    ]
