# Generated by Django 3.1.7 on 2021-05-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210513_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpets',
            name='found_petImagePath',
            field=models.ImageField(blank=True, default=None, upload_to='Found_Pets_images', verbose_name='Фото животного'),
        ),
    ]
