# Generated by Django 3.1.7 on 2021-05-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210514_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpets',
            name='found_petImagePath',
            field=models.ImageField(blank=True, default='media/None Image/none_image.jpg', upload_to='Found_Pets_images', verbose_name='Фото животного'),
        ),
    ]
