# Generated by Django 3.1.7 on 2021-05-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210514_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpets',
            name='found_petImagePath',
            field=models.FileField(blank=True, default='Found_Pets_images/none_image.jpg', upload_to='Found_Pets_images', verbose_name='Фото животного'),
        ),
        migrations.AlterField(
            model_name='foundpets',
            name='found_pet_breed',
            field=models.CharField(blank=True, default='Неизвестно', max_length=60, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='foundpets',
            name='found_pet_name',
            field=models.CharField(blank=True, default='Неизвестно', max_length=45, verbose_name='Кличка'),
        ),
    ]
