# Generated by Django 3.1.7 on 2021-05-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210514_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpets',
            name='found_petImagePath',
            field=models.ImageField(blank=True, default='Found_Pets_images/none_image.jpg', upload_to='Found_Pets_images', verbose_name='Фото животного'),
        ),
    ]
