# Generated by Django 3.1.7 on 2021-05-14 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_auto_20210514_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='pet_breed_idpet_breed',
        ),
        migrations.AddField(
            model_name='foundpets',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lostpets',
            name='lost_petImagePath',
            field=models.ImageField(blank=True, default='Lost_Pets_images/none_image.jpg', upload_to='Lost_Pets_images', verbose_name='Фото животного'),
        ),
        migrations.AlterField(
            model_name='lostpets',
            name='lost_pet_status',
            field=models.CharField(blank=True, choices=[('Пропало', 'Пропало'), ('Дома', 'Дома')], default='Пропало', max_length=15, verbose_name='Статус животного'),
        ),
    ]
