# Generated by Django 3.1.7 on 2021-05-15 13:58

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_lostpets_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpets',
            name='found_pet_status',
            field=models.CharField(blank=True, choices=[('Найдено', 'Найдено'), ('Дома', 'Дома')], default='Найдено', max_length=15, verbose_name='Статус животного'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='petImagePath',
            field=models.ImageField(upload_to=core.models.upload_location_pets, verbose_name='Фото животного'),
        ),
    ]
