# Generated by Django 3.1.7 on 2021-05-15 14:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20210515_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpets',
            name='found_petImagePath',
            field=models.ImageField(blank=True, default='Found_Pets_images/none_image.jpg', upload_to=core.models.upload_location_f_pets, verbose_name='Фото животного'),
        ),
        migrations.AlterField(
            model_name='lostpets',
            name='lost_petImagePath',
            field=models.ImageField(blank=True, default='Lost_Pets_images/none_image.jpg', upload_to=core.models.upload_location_l_pets, verbose_name='Фото животного'),
        ),
    ]
