# Generated by Django 3.1.7 on 2021-05-16 11:56

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210515_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(blank=True, default=None, max_length=150, verbose_name='Email контакта'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_phone',
            field=phone_field.models.PhoneField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_two_phone',
            field=phone_field.models.PhoneField(blank=True, default=None, max_length=20, verbose_name='Запасной номер телефона'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_director_email',
            field=models.EmailField(blank=True, default=None, max_length=45, verbose_name='Email Организатора'),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_director_phone',
            field=phone_field.models.PhoneField(default=None, max_length=45, verbose_name='Телефон Организатора'),
        ),
        migrations.AlterField(
            model_name='foundpets',
            name='found_contact_email',
            field=models.EmailField(blank=True, default=None, max_length=45, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='foundpets',
            name='found_contact_phone',
            field=phone_field.models.PhoneField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='lostpets',
            name='lost_contact_email',
            field=models.EmailField(blank=True, default=None, max_length=45, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='lostpets',
            name='lost_contact_phone',
            field=phone_field.models.PhoneField(max_length=20, verbose_name='Номер телефона'),
        ),
    ]
