# Generated by Django 3.1.7 on 2021-05-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20210516_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='pet_accustomed_to_a_leash',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет'), ('Неважно', 'Неважно')], default=None, max_length=20, verbose_name='Приучен к поводку'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_attitude_cat',
            field=models.CharField(blank=True, choices=[('Доброжелательное', 'Доброжелательное'), ('Равнодушное', 'Равнодушное'), ('Агрессивное', 'Агрессивное')], default=None, max_length=30, verbose_name='Ориентированность на котов'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_attitude_children',
            field=models.CharField(blank=True, choices=[('Доброжелательное', 'Доброжелательное'), ('Равнодушное', 'Равнодушное'), ('Агрессивное', 'Агрессивное')], default=None, max_length=30, verbose_name='Ориентированность на детей'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_attitude_other_pets',
            field=models.CharField(blank=True, choices=[('Доброжелательное', 'Доброжелательное'), ('Равнодушное', 'Равнодушное'), ('Агрессивное', 'Агрессивное')], default=None, max_length=30, verbose_name='Ориентированность на других собак'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_human_centred',
            field=models.CharField(blank=True, choices=[('Суперобщительный', 'Суперобщительный'), ('Общительный', 'Общительный'), ('Сдержанный', 'Сдержанный')], default=None, max_length=30, verbose_name='Ориентированность на людей'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_live_in_apartment',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет'), ('Неважно', 'Неважно')], default=None, max_length=20, verbose_name='Приучен к жизни в квартире'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_temperament',
            field=models.CharField(choices=[('Спокойный', 'Спокойный'), ('Активный', 'Активный'), ('Лежебока', 'Лежебока')], max_length=30, verbose_name='Темперамент'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_training',
            field=models.CharField(blank=True, choices=[('Да', 'Да'), ('Нет', 'Нет'), ('Неважно', 'Неважно')], default=None, max_length=20, verbose_name='Приучен к дрессировкам'),
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_type',
            field=models.CharField(choices=[('Семейная', 'Семейная'), ('Охотничья', 'Охотничья'), ('Охраник', 'Охраник')], max_length=100, verbose_name='Тип'),
        ),
    ]
