# Generated by Django 3.1.7 on 2021-05-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20210521_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpets',
            name='found_pet_size',
            field=models.CharField(choices=[('Крошечный', 'Крошечный'), ('Небольшой', 'Небольшой'), ('Средний', 'Средний'), ('Крупный', 'Крупный')], default=None, max_length=15, verbose_name='Размер'),
        ),
    ]
