# Generated by Django 3.1.7 on 2021-05-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20210521_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundpets',
            name='found_pet_gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], default=None, max_length=10, verbose_name='Пол'),
        ),
    ]
