# Generated by Django 3.1.7 on 2021-05-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20210521_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='pet_toilet',
        ),
        migrations.AlterField(
            model_name='pets',
            name='pet_status',
            field=models.CharField(choices=[('Ищет дом', 'Ищет дом'), ('Нашел дом', 'Нашел дом')], default='Ищет дом', max_length=15, verbose_name='Статус животного'),
        ),
    ]
