# Generated by Django 3.1.7 on 2021-05-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20210523_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='pet_sterilization',
            field=models.CharField(choices=[('Да', 'Да'), ('Частично', 'Частично'), ('Нет', 'Нет'), ('-не уточнено-', '-не уточнено-')], default='-не уточнено-', max_length=15, verbose_name='Стерилизация'),
        ),
    ]
