# Generated by Django 3.1.7 on 2021-05-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210523_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='pet_privicies',
            field=models.TextField(blank=True, default=None, max_length=500, verbose_name='Особенности'),
        ),
    ]
