# Generated by Django 3.1.7 on 2021-05-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20210523_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelters',
            name='shelter_place',
            field=models.CharField(blank=True, choices=[('Муниципальный приют', 'Муниципальный приют'), ('Частный приют', 'Частный приют')], default='Не указано', max_length=45, verbose_name='Тип приюта'),
        ),
    ]
