# Generated by Django 3.1.7 on 2021-05-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20210523_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelters',
            name='shelter_name',
            field=models.CharField(blank=True, default='-не уточнено-', max_length=45, verbose_name='Название приюта'),
        ),
        migrations.AlterField(
            model_name='shelters',
            name='shelter_place',
            field=models.CharField(blank=True, choices=[('Муниципальный приют', 'Муниципальный приют'), ('Частный приют', 'Частный приют')], default='Муниципальный приют', max_length=45, verbose_name='Тип приюта'),
        ),
    ]
