# Generated by Django 3.1.7 on 2021-05-23 17:17

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20210523_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_email',
            field=models.EmailField(blank=True, default='-не уточнено-', max_length=150, verbose_name='Email контакта'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_two_name',
            field=models.CharField(blank=True, default='-не уточнено-', max_length=45, verbose_name='Запасное Имя'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_two_phone',
            field=phone_field.models.PhoneField(blank=True, default='-не уточнено-', max_length=20, verbose_name='Запасной номер телефона'),
        ),
    ]
